version: '2'
services:
  elasticsearch.workshop-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch-workshop-1
    environment:
      - "cluster.name=elasticsearch-workshop" ## Set the cluster name
      - "node.name=elasticsearch" ## Set the node name
      - "network.host= 0.0.0.0" ##Sets binding ip to all interfaces
      - "xpack.security.enabled=false" ## Disable security
      - "xpack.monitoring.enabled=false" ## Disable monitoring
      - "xpack.graph.enabled=false" ## Disable graph
      - "xpack.watcher.enabled=false" ## Disable watcher
      - "xpack.ml.enabled=false" ## Disable machine learning
      - "bootstrap.memory_lock=true" ## Disables memory swapping
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m" ## Sets allocated memory
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
     - /Users/gs_manuel/Desktop/Git-projects/gs_Manuel-searchAcademy-assigment/API-WEB/src/main/resources/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

 # cerebro:
  #  image: cerebro-0.8.1
  #  container_name: cerebro-workshop
   # ports:
  #    - 9000:9000
  #  external_links:
  #    - elasticsearch.workshop-1:elasticsearch1
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    container_name: kibana-workshop
    ports:
      - 5601:5601
    external_links:
      - elasticsearch.workshop-1:elasticsearch1
    environment:
      ELASTICSEARCH_URL: http://elasticsearch1:9200